### ISSUE TITLE
Qgas pending transactions dont appear on Linux-Desktop app

### ISSUE THREAD

**Issue by jmmontanana** [qlcchain/sms-billing#20]
I am using the sms-biling desktop app for Linux v1.0.1 from git-hub on THE REAL network.
I waited for a while until it says that it is synchronized

but then I saw that there is not any pending transactions of my Qgas, and should show some as I can see on the web-interface.

I can see this error too many times to count on the terminal where I started the sms-billing-desktop-app:

{"level":"error","ts":1566185971.15234,"logger":"p2p","caller":"p2p/stream.go:276","msg":"send ctrl message to [QmYFMhT9nXPo3Rw3Mrbk9nqZZaKhayZipHENSuYSJjhva6] timeout","stacktrace":"github.com/qlcchain/go-qlc/p2p.(*Stream).SendMessageToCtrlChan\n\t/source/p2p/stream.go:276\ngithub.com/qlcchain/go-qlc/p2p.(*Stream).SendMessageToPeer\n\t/source/p2p/stream.go:221\ngithub.com/qlcchain/go-qlc/p2p.(*QlcNode).SendMessageToPeer\n\t/source/p2p/node.go:282\ngithub.com/qlcchain/go-qlc/p2p.(*QlcService).SendMessageToPeer\n\t/source/p2p/qlcService.go:163\ngithub.com/qlcchain/go-qlc/p2p.(*MessageService).onPublishReq\n\t/source/p2p/messageMonitor.go:366\ngithub.com/qlcchain/go-qlc/p2p.(*MessageService).publishReqLoop\n\t/source/p2p/messageMonitor.go:202"}

**Comment by pwc5232759** [comment]
thank you for your feedback, can you tell me your qlc address?

**Comment by jmmontanana** [comment]
I prefer to not make public my address

Can you write me to my email address jmmontanana@gmail.com?

and I will sent it to you

**Comment by pwc5232759** [comment]
ok

**Comment by ze-rix** [comment]
thank you for your feedback, it should be fixed in v1.0.2, please reopen the issue if the problem persists
