### ISSUE TITLE
v1.0.1 doesn't claim pending QGAS

### ISSUE THREAD

**Issue by MoreHardworking** [qlcchain/sms-billing#22]
Can you fix the claiming pending tx of Qgas on version 1.0.1?

Users manage to claim them by combining both versions (1.0.0 and 1.0.1) as:

Start wallet v1.0.1 and let it sync, then shutdown, open wallet v1.0.0 and it will claim your TX, then shutdown and start v1.0.1, shortly after you see it reflected on the web-explorer

v1.0.0 does no longer sync, but claim your pending tx successfully
v1.0.1 does not  claim your QGAS, but syncs

**Comment by ze-rix** [comment]
should be fixed in v1.0.2
