### ISSUE TITLE
SMSBilling.1.0.1 for windows miss one image file

### ISSUE THREAD

**Issue by MoreHardworking** [qlcchain/sms-billing#24]
I can see one error when I open the developing tags.

Error:  GET file:///C:/assets/img/qlc-i /C:/assets/img/qlc-i_success-green.svg:1con-staking-success-green.svg net::ERR_FILE_NOT_FOUND

**Comment by ze-rix** [comment]
thank you for your feedback, it should be fixed in v1.0.2, please reopen the issue if you find any other missing picture
