### ISSUE TITLE
make a drop down in the staking period instead of manually input 

### ISSUE THREAD

**Issue by txdzhang** [qlcchain/sms-billing#4]
![image](https://user-images.githubusercontent.com/41662938/58645426-42c32c00-82fb-11e9-88d7-9bc830b632c7.png)

**Comment by txdzhang** [comment]
Also on the invoking a new staking page
the wording of  "STAKING WILL END ON" should change to "OPTION TO REVOKE ON" 

add a line following below "You can continue to receive Q-Gas if not revoke"

**Comment by flipsum0** [comment]
dismissed the dropdown solution - instead disabled the "staking period" input (readonly) and now pre-setting the fixed value when selecting staking types (radio buttons)
