### ISSUE TITLE
letters blocked in UI

### ISSUE THREAD

**Issue by txdzhang** [qlcchain/sms-billing#6]
![image](https://user-images.githubusercontent.com/41662938/58699955-bb2afb00-8396-11e9-8953-7ce2616accfd.png)

**Comment by txdzhang** [comment]
Also, we don't need the QSMS now

**Comment by txdzhang** [comment]
Change the wording "Staking Period" to "Option to Revoke on"
on the "My staking" list

**Comment by flipsum0** [comment]
- QSMS replaced with other tokens
- "letters blocked" solved
- new wording is now "Option to Revoke on"
