### ISSUE TITLE
Staking less than 1 QLC

### ISSUE THREAD

**Issue by Zardique** [qlcchain/sms-billing#7]
In the current setup I can choose to stake less than 1 QLC,, but then my stake is stuck in no man's land, without me being able to continue invoking or get my QLC back

When you enter the duration period for the stake less than 10 days, the field automatically returns it to 10. Maybe it would be good if it could be done for QLC amount as well

For example I enter 0.1 QLC and the field auto sets it to 1 QLC

**Comment by flipsum0** [comment]
- autocorrect added to all three staking types (if smaller than minimum it's corrected to that minimum value)
